import json
import os
import uuid

def test_dynamo_dyn_generation():
    test_dir = r"D:\MCP\REVIT\scripts"
    os.makedirs(test_dir, exist_ok=True)
    dyn_path = os.path.join(test_dir, "test_generated_wall_filter.dyn")

    # Emulating DynamoHandler.GenerateGraph structure
    graph_uuid = str(uuid.uuid4())
    python_node_id = uuid.uuid4().hex
    python_out_port = uuid.uuid4().hex
    input_node_id = uuid.uuid4().hex
    input_out_port = uuid.uuid4().hex
    py_in_port = uuid.uuid4().hex
    watch_node_id = uuid.uuid4().hex
    watch_in_port = uuid.uuid4().hex
    watch_out_port = uuid.uuid4().hex

    dyn_json = {
        "Uuid": graph_uuid,
        "IsCustomNode": False,
        "Description": "Test Dynamo Graph generated by Revit MCP",
        "Name": "test_generated_wall_filter",
        "ElementResolver": {"ResolutionMap": {}},
        "Inputs": [],
        "Outputs": [],
        "Nodes": [
            {
                "ConcreteType": "CoreNodeModels.Input.StringInput, CoreNodeModels",
                "Id": input_node_id,
                "NodeType": "ExtensionNode",
                "InputValue": "Generic - 200mm",
                "Inputs": [],
                "Outputs": [
                    {
                        "Id": input_out_port,
                        "Name": "",
                        "Description": "TargetWallType",
                        "UsingDefaultValue": False,
                        "Level": 2,
                        "UseLevels": False,
                        "KeepListStructure": False
                    }
                ]
            },
            {
                "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
                "NodeType": "PythonScriptNode",
                "Code": "import clr\nclr.AddReference('RevitAPI')\nfrom Autodesk.Revit.DB import *\ncollector = FilteredElementCollector(doc).OfClass(Wall)\nOUT = [w.Name for w in collector if IN[0] in w.Name]",
                "Engine": "CPython3",
                "VariableInputPorts": True,
                "Id": python_node_id,
                "Inputs": [
                    {
                        "Id": py_in_port,
                        "Name": "IN[0]",
                        "Description": "Input #0",
                        "UsingDefaultValue": False,
                        "Level": 2,
                        "UseLevels": False,
                        "KeepListStructure": False
                    }
                ],
                "Outputs": [
                    {
                        "Id": python_out_port,
                        "Name": "OUT",
                        "Description": "Result of python script",
                        "UsingDefaultValue": False,
                        "Level": 2,
                        "UseLevels": False,
                        "KeepListStructure": False
                    }
                ]
            },
            {
                "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
                "NodeType": "ExtensionNode",
                "Id": watch_node_id,
                "Inputs": [
                    {
                        "Id": watch_in_port,
                        "Name": "",
                        "Description": "Node to evaluate",
                        "UsingDefaultValue": False,
                        "Level": 2,
                        "UseLevels": False,
                        "KeepListStructure": False
                    }
                ],
                "Outputs": [
                    {
                        "Id": watch_out_port,
                        "Name": "",
                        "Description": "Node output",
                        "UsingDefaultValue": False,
                        "Level": 2,
                        "UseLevels": False,
                        "KeepListStructure": False
                    }
                ]
            }
        ],
        "Connectors": [
            {
                "Start": input_out_port,
                "End": py_in_port,
                "Id": uuid.uuid4().hex
            },
            {
                "Start": python_out_port,
                "End": watch_in_port,
                "Id": uuid.uuid4().hex
            }
        ],
        "Dependencies": [],
        "NodeViews": [
            {
                "Id": input_node_id,
                "Name": "TargetWallType",
                "IsSetAsInput": True,
                "IsSetAsOutput": False,
                "Excluded": False,
                "ShowGeometry": True,
                "X": 100.0,
                "Y": 100.0
            },
            {
                "Id": python_node_id,
                "Name": "Python Filter (CPython 3)",
                "IsSetAsInput": False,
                "IsSetAsOutput": False,
                "Excluded": False,
                "ShowGeometry": True,
                "X": 500.0,
                "Y": 100.0
            },
            {
                "Id": watch_node_id,
                "Name": "Watch (Filtered Walls)",
                "IsSetAsInput": False,
                "IsSetAsOutput": True,
                "Excluded": False,
                "ShowGeometry": True,
                "X": 900.0,
                "Y": 100.0
            }
        ],
        "Annotations": [],
        "X": 0.0,
        "Y": 0.0,
        "Zoom": 1.0
    }

    with open(dyn_path, "w", encoding="utf-8") as f:
        json.dump(dyn_json, f, indent=2)

    print(f"[OK] Created valid Dynamo graph at: {dyn_path}")
    
    # Verify parsing
    with open(dyn_path, "r", encoding="utf-8") as f:
        loaded = json.load(f)
        
    assert loaded["Uuid"] == graph_uuid
    assert len(loaded["Nodes"]) == 3
    assert len(loaded["Connectors"]) == 2
    assert len(loaded["NodeViews"]) == 3
    print("[OK] Dynamo .dyn JSON schema validated successfully!")

if __name__ == "__main__":
    test_dynamo_dyn_generation()
