using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.DB;
using Newtonsoft.Json.Linq;

namespace RevitMCP.Plugin.Handlers
{
    public static class MassingHandler
    {
        public static object CreateMass(Document doc, dynamic args)
        {
            JArray points = (JArray)args.points;
            double height = (double)args.height;
            
            // Create Loop
            List<Curve> curves = new List<Curve>();
            List<XYZ> xyzPoints = new List<XYZ>();
            foreach (var p in points)
            {
                xyzPoints.Add(new XYZ((double)p["x"], (double)p["y"], (double)p["z"]));
            }

            CurveLoop loop = new CurveLoop();
            for (int i = 0; i < xyzPoints.Count; i++)
            {
                XYZ p1 = xyzPoints[i];
                XYZ p2 = xyzPoints[(i + 1) % xyzPoints.Count];
                loop.Append(Line.CreateBound(p1, p2));
            }
            
            List<CurveLoop> loops = new List<CurveLoop> { loop };

            // Create Solid
            Solid solid = GeometryCreationUtilities.CreateExtrusionGeometry(loops, XYZ.BasisZ, height);

            // Create DirectShape
            DirectShape ds = DirectShape.CreateElement(doc, new ElementId(BuiltInCategory.OST_Mass));
            ds.SetShape(new List<GeometryObject> { solid });
            ds.Name = "Mass Generated by MCP";

            return new { id = ds.Id.ToString(), name = ds.Name };
        }
    }
}
